like-lion-3team/trip

- src/main/java/com/traveloper/tourfinder/Controller.java
> test: branch 테스트

- README.md
> Feat(auth): 회원 가입 기능 구현

- .github/workflows/auto-assign.yml
github actions의 워크플로우
like-lion-3team ( organization ) 
trip ( repository ) 
모든 멤버에게 리뷰요청
> Chore(workflow): 자동 리뷰어 할당

- .github/workflows/auto-assign.yml
auto assign pr생성자로 자동 할당
리뷰어 자동 할당
> chore(workflow): auto-assign

- README.md
- PR생성시 3명의 리뷰어가 있어야 merge가 가능하도록 설정되어있는데, 리뷰어를 직접 고르는게 귀찮아서 리스트에 있는 유저들 중 랜덤으로 선택하도록 설정
2b30e24 커밋 참고
- 기존 워크플로우 수정
- 권한 관련 문제가 있어서 PR 쓰기권한 허용
> chore(workflow): 자동으로 리뷰어 3명 할당하는 워크플로우 테스트

- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/config/SwaggerConfig.java
- src/main/java/com/traveloper/tourfinder/common/config/WebSecurityConfig.java
> chore(member):서비스 뼈대 생성

- src/main/java/com/traveloper/tourfinder/auth/controller/AuthController.java
- src/main/java/com/traveloper/tourfinder/auth/service/TokenService.java
> feat(token):토큰 관련 서비스 기본 뼈대

- src/main/java/com/traveloper/tourfinder/auth/dto/TokenDto.java
- src/main/java/com/traveloper/tourfinder/auth/repo/MemberRepository.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- 로그인 기능 구현
- 토큰 전달을 위한 Dto 생성
- 로그인시 비밀번호 암호화 값 조회를 위한 조건문
- 존재하지 않는 유저일 때 에러처리
> feat(login):로그인 기능 구현

- build.gradle
- src/main/java/com/traveloper/tourfinder/auth/controller/AuthController.java
- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/common/AppConstants.java
- src/main/java/com/traveloper/tourfinder/common/RedisRepo.java
- 레디스 사용을 위한 세팅
- 토큰 만료시간 등 공통 값을 하드코딩 해야하는 불편함
- Redis 세팅 26b25cc
- Redis 메서드 정의 599efa1
- 공통 상수 정의 599efa1
- 토큰 삭제 메서드 추가 8dd2e7b
사용 가이드
```java 
private final RedisRepo redisRepo;
public void login(
String email,
String password
) {
redisRepo.saveRefreshToken("AccessToken","RefreshToken");
redisRepo.getRefreshToken("AccessToken")
... 기타 로직
}
```
공통 상수 사용 예시
**`common/AppConstants`**  파일에 공통 상수가 정의되어 있습니다.
```java
public class RedisRepo {
private RedisTemplate<String, String> redisTemplate;
public void saveRefreshToken(String key, String value) {
redisTemplate.opsForValue().set(key, value,AppConstants.REFRESH_TOKEN_EXPIRE_SECOND, TimeUnit.SECONDS);
}
}
```
> feat(redis): 레디스 관련 설정 및 메서드 구현, 공통 상수 정의

- src/main/java/com/traveloper/tourfinder/auth/repo/MemberRepository.java
- 누락된 사항 추가
- Member Repository 수정
> fix(login):로그인 repository 수정

- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- 비밀번호 비교로직 암호화 단계 누락
- 비밀번호 비교 로직 수정
> fix(login):비밀번호 비교로직 수정

- src/main/java/com/traveloper/tourfinder/common/config/SwaggerConfig.java
- 토큰 인증 테스트를 하기가 어려워서
- 토큰 인증란 생성
> chore(swagger): swagger 토큰 인증란 생성

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/SignInDto.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- 로그인 필수값 dto로 관리
- swagger 테스트 데이터 입력
> fix(login):로그인 dto 정의, swagger 테스트 데이터 입력

- src/main/java/com/traveloper/tourfinder/common/util/ValidateUtils.java
- 유효성 검증 유틸리티 클래스 생성
- 비밀번호 검증 메서드 생성
- 이메일 검증 메서드 생성
> feat(validate): 비밀번호, 이메일 유효성 검증 유틸리티 클래스

- src/main/java/com/traveloper/tourfinder/TestController.java
- src/main/java/com/traveloper/tourfinder/api/naver/developers/config/NDClientConfig.java
- src/main/java/com/traveloper/tourfinder/api/naver/developers/service/NDApiService.java
- src/main/java/com/traveloper/tourfinder/api/naver/developers/service/NDSearchService.java
- src/main/java/com/traveloper/tourfinder/common/config/WebSecurityConfig.java
- src/main/resources/application.yaml
- feat/api
- 네이버의 지역검색 api를 사용하는 service를 추가했습니다.
> feat(api): 지역검색 api 개발

- src/main/java/com/traveloper/tourfinder/place/controller/TripPlaceController.java
- src/main/java/com/traveloper/tourfinder/place/entity/TripPlace.java
- src/main/java/com/traveloper/tourfinder/place/repo/TripPlaceRepository.java
- src/main/java/com/traveloper/tourfinder/place/service/TripPlaceService.java
feat/trip-places
- 여행지 관련 정보 기본 세팅
> feat(trip-places):  여행지 관련 Controller, Service, Entity, Repo 생성

- src/main/java/com/traveloper/tourfinder/board/controller/ArticleController.java
- src/main/java/com/traveloper/tourfinder/board/controller/BoardController.java
- src/main/java/com/traveloper/tourfinder/board/controller/CommentController.java
- src/main/java/com/traveloper/tourfinder/board/dto/ArticleDto.java
- src/main/java/com/traveloper/tourfinder/board/dto/BoardDto.java
- src/main/java/com/traveloper/tourfinder/board/dto/CommentDto.java
- src/main/java/com/traveloper/tourfinder/board/entity/Article.java
- src/main/java/com/traveloper/tourfinder/board/entity/Board.java
- src/main/java/com/traveloper/tourfinder/board/entity/Comment.java
- src/main/java/com/traveloper/tourfinder/board/repo/ArticleRepository.java
- src/main/java/com/traveloper/tourfinder/board/repo/BoardRepository.java
- src/main/java/com/traveloper/tourfinder/board/repo/CommentRepository.java
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/java/com/traveloper/tourfinder/board/service/BoardService.java
- src/main/java/com/traveloper/tourfinder/board/service/CommentService.java
> feat(board): 게시판 Controller,Service,Entity,Dto,Repo 생성

- src/main/java/com/traveloper/tourfinder/auth/controller/EmailController.java
- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/controller/TokenController.java
- src/main/java/com/traveloper/tourfinder/auth/controller/TokenService.java
- src/main/java/com/traveloper/tourfinder/auth/service/EmailService.java
- 충돌 최소화 및 개발 편의
- 서비스 및 컨트롤러 분리
- 기본 엔드포인트 정의
> chore(separation): 개발 편의를 위한 서비스 분리

- build.gradle
- src/main/java/com/traveloper/tourfinder/auth/controller/EmailController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/VerifyCodeSendSuccessDto.java
- src/main/java/com/traveloper/tourfinder/auth/service/EmailService.java
- src/main/java/com/traveloper/tourfinder/common/AppConstants.java
- src/main/java/com/traveloper/tourfinder/common/RedisRepo.java
- src/main/java/com/traveloper/tourfinder/common/util/RandomCodeUtils.java
- src/main/resources/application.yaml
- src/test/java/com/traveloper/tourfinder/common/util/RandomCodeUtilsTest.java
- application.yaml 세팅 603ae33
- 이메일 전송 기능구현 b4a2753
- 랜덤코드 생성 유틸리티 클래스 생성 6e50a2f
- 레디스 저장 기능 구현 79e13b0
- 이메일 인증코드 검증 기능 구현 e824f14
**application.yaml에 환경변수가 추가되었습니다. IDE에서 환경변수를 추가해주세요**
구글의 SMTP 서버를 사용하고 있습니다.  아래 링크 참고해주세요
https://ajdahrdl.tistory.com/236
> feat(email):이메일 전송에 필요한 기능들 구현

- src/main/java/com/traveloper/tourfinder/admin/controller/AdminAuthController.java
- src/main/java/com/traveloper/tourfinder/admin/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/admin/dto/PeriodDto.java
> chore(admin):관리자 기능 기본 세팅

- src/main/java/com/traveloper/tourfinder/course/entity/Course.java
- src/main/java/com/traveloper/tourfinder/place/entity/TripPlace.java
> fix(entity):테이블 생성 관련 오류 수정

- src/main/java/com/traveloper/tourfinder/admin/controller/AdminMemberController.java
- src/main/java/com/traveloper/tourfinder/admin/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/view/AdminViewController.java
- src/main/resources/templates/admin-dashboard.html
> fix(admin): 클래스명 중복으로 인한 에러 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/RedisRepo.java
> feat(Member): Controller(로그아웃),Service(sendCode, VerifyCode)

- src/main/java/com/traveloper/tourfinder/admin/controller/AdminAuthController.java
- src/main/java/com/traveloper/tourfinder/admin/controller/AdminMemberController.java
- src/main/java/com/traveloper/tourfinder/admin/repo/AdminMemberRepo.java
- src/main/java/com/traveloper/tourfinder/admin/service/AdminMemberService.java
- src/main/java/com/traveloper/tourfinder/admin/service/AdminService.java
- src/main/java/com/traveloper/tourfinder/auth/repo/RoleRepository.java
- src/main/java/com/traveloper/tourfinder/common/config/WebSecurityConfig.java
- src/main/java/com/traveloper/tourfinder/view/AdminViewController.java
- src/main/resources/templates/admin-login.html
- src/test/java/com/traveloper/tourfinder/admin/AdminMemberServiceTest.java
- 관리자 로그인 기능 구현
- 회원 차단 해제 기능
- 테스트 코드
- 로그인 화면 구현
**로그인**
**로그인 성공**
**로그인 성공시 페이지 이동**
Member 테이블에 관리자용 계정 만드신 후 테스트 해보시면 됩니다.
> feat(admin): 관리자 기능 구현

- src/main/resources/templates/sample-course-create.html
- feat/places
- 키워드 검색 결과 리스트들의 title만 (임시로) 화면에 출력되도록 구현 
- 여행지의 contentId 를 바탕으로 각 여행지의 상세 정보 모달창 구현
> feat(places): 여행지 검색 결과 리스트, 상세정보 모달창 보여주기

- build.gradle
- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/common/config/WebSecurityConfig.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/data.sql
- src/main/resources/templates/admin-dashboard.html
- src/main/resources/templates/common.css
- src/main/resources/templates/login.html
- src/main/resources/templates/signUp.html
- 관리자 대시보드 ui 수정
- 로그인 화면 ui 수정
- cors 설정
**일반 사용자 로그인 화면**
**회원 관리 대시보드**
**유저 회원가입 화면**
> fix(ui): 관리자 대시보드 ui수정, 로그인 화면 ui 수정, 회원가입 화면 구현

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/PasswordDto.java
- src/main/java/com/traveloper/tourfinder/auth/repo/MemberRepository.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
> feat(login): PasswordDto 추가, Service upDatePassword 추가

- src/main/java/com/traveloper/tourfinder/auth/dto/SignInDto.java
- src/main/resources/data.sql
- swagger 에 기본값으로 입력해둔 더미데이터와 실제 DB 데이터가 다름
- 더미데이터 수정
> fix(dummy):더미 데이터 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/MyPageDto.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
> feat(api):마이페이지 에서 사용할 api

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- 응답 객체 형식이 통일되어 있지 않음
- 차단된 사용자 검증 누락
- 회원가입 엔드포인트 응답 객체 형식 수정
- 로그인시 차단된 사용자 검증
> fix(api):회원가입, 로그인 api 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
> fix(controller):memberController 충돌 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/jwt/JwtTokenUtils.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/AppConstants.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/common/config/WebSecurityConfig.java
- src/main/java/com/traveloper/tourfinder/common/exception/CustomGlobalErrorCode.java
- src/main/java/com/traveloper/tourfinder/common/exception/CustomJwtExceptionFilter.java
- 토큰 생성, 검증, 삭제 처리 누락
- 로그아웃시 redis 저장소에서 토큰 모두 삭제
- 매 요청시 redis저장소에 accessToken이 저장되어있는지 체크
- 로그인시 redis 저장소에 토큰 저장
- 토큰 만료시간 공통 상수 적용
- jwt 유틸리티 클래스 수정
> fix(auth): 토큰 생명주기 관련 수정사항

- src/main/java/com/traveloper/tourfinder/board/controller/ArticleController.java
- src/main/java/com/traveloper/tourfinder/board/dto/ArticleDto.java
- src/main/java/com/traveloper/tourfinder/board/repo/ArticleRepository.java
- src/main/java/com/traveloper/tourfinder/board/repo/ArticleTagRepository.java
- src/main/java/com/traveloper/tourfinder/board/repo/TagRepository.java
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- feat/article -> feat/board
- articleDto, Entity 수정 및, article CRUD 기능 개발
> feat(article): article CRUD 작성

- src/main/resources/static/css/sample-map.css
- src/main/resources/templates/sample-map.html
- feat/select-places
- 여행지 검색 결과 우측에 배치
- 임시 코스 생성 form 작성
> feat(select-places): 코스 생성 form 작성

- src/main/resources/templates/login.html
- src/main/resources/templates/my-page.html
- 마이페이지 더미 데이터를 실제 데이터로 변경
- 데이터 조회 스크립트 작성
- 토큰 만료 혹은 기타 토큰 이슈 생기면 재발급 요청 처리
- 최종 처리 실패시 다시 로그인 페이지로 이동
> fix(html):마이페이지 데이터 조회 스크립트 작성

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- 누락 사항 반영
- 이메일 변경 기능 삭제
- 로그인 할 때 이메일을 사용해서 변경 하면 안될 것 같다고 이전에 이야기 했던 사항 반영했습니다.
> fix(auth):이메일 변경 기능 삭제

- src/main/java/com/traveloper/tourfinder/board/controller/ArticleController.java
- src/main/java/com/traveloper/tourfinder/board/entity/ArticleLike.java
- src/main/java/com/traveloper/tourfinder/board/repo/ArticleLikeRepository.java
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- feat/article -> feat/board
- 게시글 좋아요  토글 기능 추가
> feat(article): 좋아요 토글 기능 추가

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- feat/recoverPW
- MemberController(비밀번호 수정) 수정
> Fix(member): MemberController(비밀번호 수정) 수정

- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/java/com/traveloper/tourfinder/board/service/CommentServiceImp.java
- src/main/java/com/traveloper/tourfinder/common/exception/CustomGlobalErrorCode.java
- src/main/java/com/traveloper/tourfinder/course/service/CourseService.java
- fix/exception
- 준수님이 제작하신 GlobalException 방식으로 예외처리를 변경했습니다.
> fix(exception): Course와 Board에 관한 예외 GlobalException으로 변경

- src/main/java/com/traveloper/tourfinder/board/dto/ArticleDto.java
- src/main/java/com/traveloper/tourfinder/board/entity/Article.java
- src/main/java/com/traveloper/tourfinder/board/entity/ArticleLike.java
- src/main/java/com/traveloper/tourfinder/board/entity/ArticleTag.java
- src/main/java/com/traveloper/tourfinder/board/entity/Comment.java
- src/main/java/com/traveloper/tourfinder/board/entity/Tag.java
- dev
- 게시판 관련 엔티티에서 @SuperBuilder를 사용하지 않아 생기는 문제가 있어서 @Builder대신 @SuperBuilder로 바꿨습니다.
> fix(board):  SuperBuilder를 사용하지 않아 오류나는 문제 해소

- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/static/js/details-places.js
- src/main/resources/static/js/marker-places.js
- src/main/resources/static/js/search-places.js
- src/main/resources/templates/sample-course-read.html
- course
- 로컬 스토리지 토큰 사용하도록 변경, Permit Pattern에 sign-up 추가
> fix(course): 로컬 스토리지 토큰 사용하도록 변경, Permit Pattern에 sign-up 추가

- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/static/css/sample-map.css
- src/main/resources/static/js/marker-places.js
- src/main/resources/static/js/sample-course-create.js
- src/main/resources/static/js/search-places.js
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/home.html
- src/main/resources/templates/sample-map.html
- feat(map-design)
- 코스 생성 페이지를 처음 로딩할 떄 보였던 검색어를 입력하시오 알람문구가 더이상 보이지 않도록 설정
- 코스 생성 버튼 클릭시 Bear 토큰을 헤더에 추가하는 부분 추가
- 코스에 추가하기 버튼, 선택된 여행지 리스트를 클릭할 시 해당 여행지 좌표 중심지로 화면 이동
- 홈 화면 생성
- 홈 화면에 코스 만들어보기 링크 생성
> feat(map-design): 여행지 setCenter 설정, 홈 화면으로 가는 링크 생성

- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/templates/article-update.html
- board
- 게시글 작성 시 태그 기능
- 게시글 수정을 위한 폼 (이미지 부분은 미완)
> feat(article): 게시글 작성 폼 태그 기능 추가, 게시글 수정 폼 작업물

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/course/controller/CourseController.java
- src/main/java/com/traveloper/tourfinder/course/service/CourseService.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/sample-course-list-test.html
- feat/course-list
- DB에 저장된 모든 코스들을 코스 목록에 표시
> feat(course-list): 코스 목록 표시

- src/main/java/com/traveloper/tourfinder/oauth2/controller/SocialController.java
- src/main/java/com/traveloper/tourfinder/oauth2/dto/NaverTokenResponse.java
- src/main/java/com/traveloper/tourfinder/oauth2/dto/NaverUserProfile.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/NaverOauthService.java
- src/main/resources/application.yaml
- src/main/resources/data.sql
- 네이버 로그인 연동
- 더미 데이터 ( NAVER ) 추가
http://localhost:8080/api/v1/oauth2/naver
에서 테스트 할 수 있습니다.
네이버 관련 환경 변수를 반드시 적용 해주세요
> feat(oauth2):소셜로그인 ( 네이버 )

- src/main/java/com/traveloper/tourfinder/oauth2/controller/SocialController.java
- src/main/java/com/traveloper/tourfinder/oauth2/dto/GoogleTokenResponse.java
- src/main/java/com/traveloper/tourfinder/oauth2/dto/GoogleUserProfile.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/GoogleOauthService.java
- src/main/resources/application.yaml
- src/main/resources/data.sql
> feat(oauth2):소셜로그인 (google)

- src/main/java/com/traveloper/tourfinder/board/controller/CommentController.java
- src/main/java/com/traveloper/tourfinder/board/dto/ArticleDto.java
- src/main/java/com/traveloper/tourfinder/board/dto/CommentDto.java
- src/main/java/com/traveloper/tourfinder/board/dto/WriterDto.java
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/application.yaml
- src/main/resources/templates/article-create.html
- src/main/resources/templates/article-read.html
- src/main/resources/templates/article-update.html
- feat/article
- 게시글 조회 및 댓글 기능 프론트입니다.
> feat(article): 게시글 조회 기능 개발, 댓글 작성 기능

- src/main/java/com/traveloper/tourfinder/oauth2/service/KakaoOauthService.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/SocialOauthService.java
> fix(oauth):이미 가입된 사용자가 소셜로그인시 마이페이지 조회 안되는 버그 수정

- src/main/resources/static/js/marker-places.js
- 코스 저장 과정 중 여행지의 lng lat 가 거꾸로 저장되는 문제 해결
> fix(place): lng lat 저장 오류 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/service/EmailService.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
> feat(memberController): 비밀번호 복구, 복구 요청

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/PasswordRecoveryMailRequestDto.java
- src/main/java/com/traveloper/tourfinder/auth/dto/PasswordRecoveryRequestDto.java
- src/main/java/com/traveloper/tourfinder/auth/dto/PasswordRecoveryVerifyCodeRequestDto.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/common/exception/CustomGlobalErrorCode.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/templates/password-change.html
- 인증코드 검증 메서드 추가
- 인증 메일 전송 메서드 수정
- 비밀번호 변경 메서드 수정
```java 
@PostMapping("/password-recovery") - 인증코드를 이메일로 전송
@PostMapping("/password-recovery/verify-code") - 인증코드를 검증 후 올바른 코드라면 비번 변경 페이지로 리다이렉트 
@PutMapping("/password-recovery") - 비번 변경 페이지에서 해당 요청으로 비번 변경
```
> fix(auth): 비밀번호 변경 관련 로직 수정

- .gitignore
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/application.yaml
- src/main/resources/templates/article-read.html
- permitAllPath가 변경되어 사진이 안뜨는 문제 발생
- 게시글 이미지 사진 저장 경로 변경
- permitAllPath에 변경된 사진 저장 경로 추가
> fix(board): 게시글 사진 안뜨는 문제 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/PasswordRecoveryRequestDto.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/exception/CustomGlobalErrorCode.java
- 마이페이지에서 변경, 비밀번호 찾기를 통한 변경 두가지 경우에 대응하기 위함
- 비밀번호 찾기에서 사용할 메서드 구현
- 마이페이지 에서 사용할 메서드 수정
비밀번호 찾기를 통한 비밀번호 변경 방식에서는 `이메일 인증코드`, `이메일`, `새 비밀번호` 세가지 값을 넣어야 합니다.
마이페이지 에서 변경 하는 방식에서는 `현재 비밀번호`, `새 비밀번호` 두가지 값을 넣어야 합니다.
> feat(auth):비밀번호 변경 메서드 추가 및 수정

- src/main/java/com/traveloper/tourfinder/oauth2/dto/SocialProviderAccessTokenRequestDto.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/GoogleOauthService.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/KakaoOauthService.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/NaverOauthService.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/SocialOauthService.java
- 조회 로직 변경 해야 할 때 복붙 하기 귀찮음
- 공통 서비스에 유저 조회 로직 구현
- 공통 서비스에 엑세스 토큰 요청 로직 구현
~~엑세스 토큰 받아오는 로직도 모듈화 하면 좋을 것 같음~~  [38c0611](https://github.com/like-lion-3team/trip/pull/139/commits/38c061174e23b7ba815676825be23727ae187b94) 추가됨
> refactor(oauth2): 유저 프로필 조회 로직 모듈화

- src/main/java/com/traveloper/tourfinder/board/controller/CommentController.java
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/resources/templates/article-create.html
- src/main/resources/templates/article-read.html
- src/main/resources/templates/article-update.html
- 게시글 수정, 삭제 기능 추가
- 댓글 삭제 기능 추가
> feat(board): 게시글 수정 삭제, 댓글 삭제 기능

- README.md
- 작업 중인 브랜치를 알려주세요.
- 현재 환경 변수 값들이 여러 사람의 정보로 섞여있는데 추후 개인 키로 변경할 때 원활하게 하기 위함
- 문서 업데이트
> docs(readme):readme 업데이트

- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/resources/templates/signUp.html
- 작업 중인 브랜치를 알려주세요.
- 이미 가입된 메일로 불필요한 메일 전송 방지
- 메일 전송하는 부분에 가입 유무 체크 로직 작성
> fix(auth): 이메일로 코드 전송시 이미 가입된 메일인지 체크 하는 로직

- README.md
> docs(readme):누락 사항 입력

- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/static/css/sample-map.css
- src/main/resources/static/js/marker-places.js
- src/main/resources/templates/my-page.html
- src/main/resources/templates/sample-course-create.html
- src/main/resources/templates/sample-course-update.html
- feat/course-update
- 코스 수정 페이지 프론트 구현 (코스 수정 페이지는 코스 생성 페이지와 거의 동일)
기존에 등록한 "부산 여행 코스"
서율 여행 코스로 수정
> feat(course-update): 코스 수정 페이지 구현

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/MemberIdDto.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/static/js/current-member.js
- src/main/resources/templates/article-read.html
- src/main/resources/templates/course-read.html
- 게시글에서 수정, 삭제 버튼과 댓글의 삭제 버튼이 이제 해당 작성자에게만 보입니다
---
> feat(board): 게시글, 댓글의 수정, 삭제 버튼이 작성자에게만 보이도록 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/templates/signUp.html
- 회원가입시 적절한 피드백이 없어서 멈춘 것 같은 기분이듬
- 회원가입시 닉네임 중복체크
- 회원가입시 이메일 인증
- 서버에서 적절한 피드백 내려주도록 수정
- 인증 없이 회원가입이 가능한 버그 수정
> fix(sign-up):회원 가입 로직 수정

- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/templates/signUp.html
- 회원가입시 접근 권한 문제 
- 접근 권한 추가 및 프론트단 409 에러 관련 부분 수정
> fix(auth):접근 권한 수정

- src/main/resources/static/js/login-logout.js
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/logout.html
- feat/logoutFront
- logout js만 추가 아직 html 미적용
> feat(logoutFront): logout js 추가

- src/main/java/com/traveloper/tourfinder/admin/controller/AdminMemberController.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/templates/admin-dashboard.html
- 관리자 페이지 안떠서 수정
- 요청 주소 127.0.0.1 -> localhost 변경
- 권한 허용 주소 추가
> fix(admin):관리자 기능 수정

- src/main/java/com/traveloper/tourfinder/admin/service/AdminService.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/resources/templates/login.html
- 관리자 로그인 로직 수정
- 로그인 페이지에서 로그인 성공시 모달 숨기는 함수 수정
> fix(auth): 로그인 관련 기능 수정

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/exception/CustomGlobalErrorCode.java
- src/main/resources/templates/password-change-email-check.html
- 소셜 회원은 비밀번호 변경이 의미가 없어서 피드백을 주도록 변경
- `MemberController` 에서 `MemberService`에 있는 메서드를 호출 하도록 수정
- 화면단에서 에러 처리시 서버에서 내려준 메시지 알림으로 띄우도록 수정
> fix(auth):비밀번호 변경 로직 수정

- src/main/java/com/traveloper/tourfinder/admin/controller/AdminMemberController.java
- src/main/java/com/traveloper/tourfinder/auth/controller/EmailController.java
- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- 일관성 있는 응답을 줘서 화면단에서 역직렬화 할 때 에러 가능성을 줄임
- `Response.ok("")` 형태로 String을 전송하던 응답을 빈 객체를 전송 하도록 수정
> fix(response): 정상 응답 시에도 일관성있는 빈json 객체 전송 하도록 수정

- src/main/java/com/traveloper/tourfinder/board/controller/ArticleController.java
- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/view/ViewController.java
- src/main/resources/templates/article-create.html
- src/main/resources/templates/article-read.html
- src/main/resources/templates/article-update.html
- src/main/resources/templates/board-articles.html
- src/main/resources/templates/fragments/header.html
- 준수님이 작업하신 프래그먼트들 적용했습니다.
- 게시글 작성자가 표시안되는 문제가 있었는데 해결했습니다.
- 댓글 수 표시를 추가했습니다.
> feat(article): 게시글 작성자 표시, 게시글 페이지에 헤더 푸터 적용, 댓글 수 표시

- src/main/resources/templates/password-change-form.html
- 비밀번호 변경 화면단 구현
- 비밀번호 변경 스크립트 작성
일반 회원가입: 회원가입 -> 비밀번호 찾기 -> 변경
소셜 회원가입: 소셜로그인(자동가입) -> 비밀번호 찾기 -> 사용불가
> fix(auth):비밀번호 변경 기능 구현

- src/main/java/com/traveloper/tourfinder/board/service/ArticleService.java
- src/main/resources/templates/board-articles.html
- 게시글 작성 버튼 추가
- 게시글이 최근에 작성된 순서대로 조회되도록 변경
- 사진은 페이지네이션을 쉽게 보기위해 size=2 로 잡고 페이지를 로딩했을 때 결과물입니다.(기본값 10)
> fix(board): 게시글 작성 버튼 추가, 게시글 id의 역순으로 조회하도록 변경

- src/main/resources/templates/board-articles.html
- 놀랍게도 게시글 클릭하면 게시글로 이동하는 기능을 빼먹어서 추가했습니다(...)
- 게시글에 마우스 올릴 시 배경색 전환 기능 추가
> fix(board): 게시글 클릭시 게시글로 이동 설정

- src/main/resources/static/js/marker-places.js
- src/main/resources/templates/course-create.html
- src/main/resources/templates/course-update.html
- feat/courses
- 코스 생성, 코스 수정 페이지에서 처음 화면이 로드될 때 로그인 정보 확인 후 필요 시 로그인 페이지로 리다이렉트
- 코스 생성, 수정 버튼 클릭 시 로그인 정보 확인 후 필요 시 로그인 페이지로 리다이렉트
> feat(courses): 코스 생성, 수정 페이지에서 회원 인증 실패시 로그인 페이지로 리다이렉트

- src/main/resources/static/css/course-read.css
- src/main/resources/templates/course-read.html
- src/main/resources/templates/signUp.html
- nickname이 반영되지 않던 문제 해결했습니다.
> fix(auth): signUp.html 에서 nickname이 반영되지 않던 문제 해결

- src/main/resources/static/css/course-read.css
- src/main/resources/templates/article-create.html
- src/main/resources/templates/article-read.html
- src/main/resources/templates/article-update.html
- src/main/resources/templates/course-read.html
> fix(course): 코스 조회 디자인 변경

- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/resources/static/js/login-logout.js
- src/main/resources/static/js/retryToken.js
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/my-page.html
- 주홍님이 작성하신 로그인 로그아웃 함수 기능 수정 및 리팩토링 했습니다.
- 로그인 / 로그아웃 상황에 맞는 버튼 표시
- 로그아웃 처리
- 토큰 재발급 함수가 Promise를 반환하도록 수정
> fix(auth):로그인 로그아웃 버튼 및 로직 수정

- src/main/java/com/traveloper/tourfinder/admin/controller/AdminMemberController.java
- src/main/java/com/traveloper/tourfinder/admin/service/AdminMemberService.java
- src/main/java/com/traveloper/tourfinder/auth/controller/MemberController.java
- src/main/java/com/traveloper/tourfinder/auth/dto/MemberDto.java
- src/main/java/com/traveloper/tourfinder/auth/entity/Member.java
- src/main/java/com/traveloper/tourfinder/auth/service/MemberService.java
- src/main/java/com/traveloper/tourfinder/common/AppConstants.java
- src/main/java/com/traveloper/tourfinder/common/config/PermitAllPath.java
- src/main/java/com/traveloper/tourfinder/oauth2/service/SocialOauthService.java
- 멤버 Entity 및 Dto에 profile 항목 추가
- 멤버 서비스 및 컨트롤러에 업로드를 위한 메서드 생성 (/api/v1/auth/profile-upload)
> feat(auth): 멤버 프로필 업로드 백엔드 작업
